---
services:
  app:
    build: ./app
    read_only: true
    restart: unless-stopped
    volumes:
      - type: tmpfs
        target: /tmp
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/example.local.crt:/example.local.crt
      - ./nginx/example.local.key:/example.local.key
      - type: tmpfs
        target: /var/cache/nginx
      - type: tmpfs
        target: /var/run
    depends_on:
      - app
  bot:
    build: ./bot
    read_only: true
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      PAGE_URL: "https://nginx"
      FLAG: "snakeCTF{REDACTED}"
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome"
    volumes:
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /root/.config
